CREATE TABLE "GCG_6946_WIP_PARENT" (
 "JOB" VARCHAR(6),
 "FREIGHT" DOUBLE,
 "MATERIAL" DOUBLE,
 "LABOR" DOUBLE,
 "OUTSIDE_PROCESS" DOUBLE,
 "OVERHEAD" DOUBLE,
 "OTHER" DOUBLE,
 "WIP" DOUBLE,
 "SALES_VALUE" DOUBLE,
 "DUE_DATE" DATE );
